/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EnteredInquiryCard: typeof import('./src/components/EnteredInquiryCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InquiryButtonPanel: typeof import('./src/components/InquiryButtonPanel.vue')['default']
    QuestionSearchBar: typeof import('./src/components/QuestionSearchBar.vue')['default']
    StatQuestionCountCard: typeof import('./src/components/StatQuestionCountCard.vue')['default']
    StatsDialog: typeof import('./src/components/StatsDialog.vue')['default']
  }
}
